name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - 'README.md'
      - '.vscode/**'
      - '.gitignore'
      - '.github/ISSUE_TEMPLATE/**'
      - 'CONTRIBUTING.md'
      - 'FUNDING.yml'

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm@9

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Build And Deploy (Production)
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_SALMON_TREE_0194D6F0F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: 'upload'
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: '/' # App source code path
          api_location: '.output/server' # Api source code path - optional
          output_location: '.output/public' # Built app content directory - optional
          skip_app_build: true
          skip_api_build: true
      - name: Deploy Dev Branch
        if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_VICTORIOUS_TREE_06155740F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          action: 'upload'
          app_location: '/'
          api_location: '.output/server'
          output_location: '.output/public'
          skip_app_build: true
          skip_api_build: true
      - name: Build And Deploy (Next)
        id: builddeploy-next
        if: github.event_name == 'pull_request' && github.event.action != 'closed' && github.base_ref == 'dev'
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_VICTORIOUS_TREE_06155740F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: 'upload'
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: '/' # App source code path
          api_location: '.output/server' # Api source code path - optional
          output_location: '.output/public' # Built app content directory - optional
          skip_app_build: true
          skip_api_build: true
