name: SWA Preview Cleanup

on:
  pull_request:
    types: [closed]

jobs:
  close_preview:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Close Preview Environment
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_VICTORIOUS_TREE_06155740F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: close
          app_location: /
          api_location: .output/server
          output_location: .output/public
